// Reusable test data factories
import { Decimal } from '@prisma/client/runtime/library';

// UUID v4 format: xxxxxxxx-xxxx-4xxx-[89ab]xxx-xxxxxxxxxxxx
const uuid = (n: number) => `00000000-0000-4000-a000-${String(n).padStart(12, '0')}`;

export const fixtures = {
  user: {
    customer: () => ({
      id: uuid(1),
      email: 'customer@test.com',
      name: 'Test Customer',
      role: 'CUSTOMER',
      phone: '010-1234-5678',
      passwordHash: '$2a$10$hashedpassword',
      profileImage: null,
      createdAt: new Date('2025-01-01'),
      updatedAt: new Date('2025-01-01'),
    }),
    admin: () => ({
      id: uuid(2),
      email: 'admin@test.com',
      name: 'Test Admin',
      role: 'ADMIN',
      phone: '010-9876-5432',
      passwordHash: '$2a$10$hashedpassword',
      profileImage: null,
      createdAt: new Date('2025-01-01'),
      updatedAt: new Date('2025-01-01'),
    }),
  },

  category: {
    top: () => ({
      id: uuid(10),
      name: '상의',
      slug: 'tops',
      parentId: null,
      depth: 0,
      sortOrder: 0,
      isActive: true,
    }),
    shirts: () => ({
      id: uuid(11),
      name: '셔츠',
      slug: 'shirts',
      parentId: uuid(10),
      depth: 1,
      sortOrder: 0,
      isActive: true,
    }),
    pants: () => ({
      id: uuid(12),
      name: '바지',
      slug: 'pants',
      parentId: null,
      depth: 0,
      sortOrder: 1,
      isActive: true,
    }),
    inactive: () => ({
      id: uuid(13),
      name: '비활성 카테고리',
      slug: 'inactive-cat',
      parentId: null,
      depth: 0,
      sortOrder: 99,
      isActive: false,
    }),
  },

  brand: {
    nike: () => ({
      id: uuid(20),
      name: 'Nike',
      slug: 'nike',
      logoUrl: '/logos/nike.png',
      description: 'Just Do It',
      isActive: true,
    }),
    adidas: () => ({
      id: uuid(21),
      name: 'Adidas',
      slug: 'adidas',
      logoUrl: '/logos/adidas.png',
      description: 'Impossible is Nothing',
      isActive: true,
    }),
  },

  product: {
    tshirt: () => ({
      id: uuid(30),
      name: '베이직 티셔츠',
      slug: 'basic-tshirt',
      description: '편안한 기본 티셔츠',
      basePrice: new Decimal(29000),
      categoryId: uuid(11),
      brandId: uuid(20),
      status: 'ACTIVE' as const,
      avgRating: new Decimal(4.5),
      reviewCount: 10,
      salesCount: 100,
      createdAt: new Date('2025-01-15'),
      updatedAt: new Date('2025-01-15'),
    }),
    jeans: () => ({
      id: uuid(31),
      name: '슬림 진',
      slug: 'slim-jeans',
      description: '슬림핏 청바지',
      basePrice: new Decimal(59000),
      categoryId: uuid(12),
      brandId: uuid(21),
      status: 'ACTIVE' as const,
      avgRating: new Decimal(4.0),
      reviewCount: 5,
      salesCount: 50,
      createdAt: new Date('2025-01-10'),
      updatedAt: new Date('2025-01-10'),
    }),
    hidden: () => ({
      id: uuid(32),
      name: '숨김 상품',
      slug: 'hidden-product',
      description: '비공개 상품',
      basePrice: new Decimal(10000),
      categoryId: uuid(10),
      brandId: null,
      status: 'HIDDEN' as const,
      avgRating: new Decimal(0),
      reviewCount: 0,
      salesCount: 0,
      createdAt: new Date('2025-01-05'),
      updatedAt: new Date('2025-01-05'),
    }),
  },

  variant: {
    tshirtM: () => ({
      id: uuid(40),
      productId: uuid(30),
      sku: 'TS-M-BLK',
      size: 'M',
      color: 'Black',
      colorCode: '#000000',
      price: new Decimal(29000),
      stock: 50,
      reservedStock: 5,
      isActive: true,
    }),
    tshirtL: () => ({
      id: uuid(41),
      productId: uuid(30),
      sku: 'TS-L-BLK',
      size: 'L',
      color: 'Black',
      colorCode: '#000000',
      price: new Decimal(29000),
      stock: 30,
      reservedStock: 0,
      isActive: true,
    }),
    tshirtMWhite: () => ({
      id: uuid(42),
      productId: uuid(30),
      sku: 'TS-M-WHT',
      size: 'M',
      color: 'White',
      colorCode: '#FFFFFF',
      price: new Decimal(29000),
      stock: 0,
      reservedStock: 0,
      isActive: true,
    }),
    jeansM: () => ({
      id: uuid(43),
      productId: uuid(31),
      sku: 'JN-M-BLU',
      size: 'M',
      color: 'Blue',
      colorCode: '#0000FF',
      price: new Decimal(59000),
      stock: 20,
      reservedStock: 2,
      isActive: true,
    }),
    inactive: () => ({
      id: uuid(44),
      productId: uuid(30),
      sku: 'TS-S-BLK',
      size: 'S',
      color: 'Black',
      colorCode: '#000000',
      price: new Decimal(29000),
      stock: 10,
      reservedStock: 0,
      isActive: false,
    }),
  },

  cart: {
    guest: () => ({
      id: uuid(50),
      userId: null,
      sessionId: 'guest-session-123',
      createdAt: new Date('2025-02-01'),
      updatedAt: new Date('2025-02-01'),
    }),
    user: () => ({
      id: uuid(51),
      userId: uuid(1),
      sessionId: null,
      createdAt: new Date('2025-02-01'),
      updatedAt: new Date('2025-02-01'),
    }),
  },

  cartItem: {
    guestItem1: () => ({
      id: uuid(60),
      cartId: uuid(50),
      variantId: uuid(40),
      quantity: 2,
    }),
    guestItem2: () => ({
      id: uuid(61),
      cartId: uuid(50),
      variantId: uuid(43),
      quantity: 1,
    }),
    userItem1: () => ({
      id: uuid(62),
      cartId: uuid(51),
      variantId: uuid(40),
      quantity: 1,
    }),
  },

  order: {
    paid: () => ({
      id: uuid(70),
      orderNumber: 'ORD-20250201-001',
      userId: uuid(1),
      status: 'PAID' as const,
      totalAmount: new Decimal(87000),
      discountAmount: new Decimal(0),
      shippingFee: new Decimal(0),
      finalAmount: new Decimal(87000),
      addressSnapshot: { name: 'Test', address1: '서울시', zipCode: '12345' },
      couponId: null,
      note: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }),
    cancelled: () => ({
      id: uuid(71),
      orderNumber: 'ORD-20250201-002',
      userId: uuid(1),
      status: 'CANCELLED' as const,
      totalAmount: new Decimal(29000),
      discountAmount: new Decimal(0),
      shippingFee: new Decimal(3000),
      finalAmount: new Decimal(32000),
      addressSnapshot: { name: 'Test', address1: '서울시', zipCode: '12345' },
      couponId: null,
      note: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }),
  },

  session: {
    customer: () => ({
      user: {
        id: uuid(1),
        email: 'customer@test.com',
        name: 'Test Customer',
        role: 'CUSTOMER',
      },
    }),
    admin: () => ({
      user: {
        id: uuid(2),
        email: 'admin@test.com',
        name: 'Test Admin',
        role: 'ADMIN',
      },
    }),
  },
};
